<?php

return [
    'user_roles' => [
        'admin' => 'Admin',
        'user' => 'User',
    ],
    'genealogy' => [
        'type' => 'binary',
        'spillover' => false,
        'max_levels' => 5,
    ],
    'commission' => [
        'direct_referral' => [
            'enabled' => true,
            'rate' => 10,
            'type' => 'percentage',
        ],
        'binary' => [
            'enabled' => true,
            'pair_amount' => 101,
            'auto_placement' => true,
            'placement_preference' => 'right',
            'capping' => [
                'enabled' => true,
                'daily_limit' => 1000,
                'weekly_limit' => 5000,
                'monthly_limit' => 20000,
            ],
            'matching_bonus' => [
                'enabled' => true,
                'levels' => [
                    1 => 10,
                    2 => 5,
                    3 => 3,
                ],
            ],
        ],
        'matrix' => [
            'enabled' => false,
            'width' => 3,
            'depth' => 5,
            'levels' => [
                1 => 10,
                2 => 8,
                3 => 6,
                4 => 4,
                5 => 2,
            ],
        ],
        'unilevel' => [
            'enabled' => false,
            'levels' => [
                1 => 8,
                2 => 5,
                3 => 3,
                4 => 2,
                5 => 2,
                6 => 1,
                7 => 1,
            ],
        ],
        'generation' => [
            'enabled' => false,
            'generations' => 5,
            'rate' => 5,
        ],
    ],
    'ranks' => [
        'auto_rank_upgrade' => true,
        'check_interval' => 'daily',
        'rank_levels' => [
            [
                'name' => 'Member',
                'slug' => 'member',
                'level' => 0,
                'minimum_sales' => 0,
                'minimum_team_sales' => 0,
                'minimum_directs' => 0,
                'bonus_amount' => 0,
            ],
            [
                'name' => 'Bronze',
                'slug' => 'bronze',
                'level' => 1,
                'minimum_sales' => 1000,
                'minimum_team_sales' => 5000,
                'minimum_directs' => 3,
                'bonus_amount' => 100,
            ],
            [
                'name' => 'Silver',
                'slug' => 'silver',
                'level' => 2,
                'minimum_sales' => 5000,
                'minimum_team_sales' => 25000,
                'minimum_directs' => 5,
                'bonus_amount' => 500,
            ],
            [
                'name' => 'Gold',
                'slug' => 'gold',
                'level' => 3,
                'minimum_sales' => 10000,
                'minimum_team_sales' => 100000,
                'minimum_directs' => 10,
                'bonus_amount' => 2000,
            ],
            [
                'name' => 'Platinum',
                'slug' => 'platinum',
                'level' => 4,
                'minimum_sales' => 25000,
                'minimum_team_sales' => 500000,
                'minimum_directs' => 20,
                'bonus_amount' => 10000,
            ],
            [
                'name' => 'Diamond',
                'slug' => 'diamond',
                'level' => 5,
                'minimum_sales' => 50000,
                'minimum_team_sales' => 1000000,
                'minimum_directs' => 50,
                'bonus_amount' => 50000,
            ],
        ],
    ],
    'registration' => [
        'require_sponsor' => true,
        'default_sponsor_username' => 'root',
        'email_verification_required' => false,
    ],
    'security' => [
        'max_login_attempts' => 5,
        'lockout_duration' => 30,
        'session_timeout' => 60,
        'require_2fa' => false,
    ],
    'payout' => [
        'min_amount' => 2,
        'max_amount' => 100000,
        'charges_percent' => 5,
        'processing_days' => 3,
        'allowed_days' => [
            'Monday',
            'Thursday',
            'Sunday',
            'Saturday',
        ],
    ],
];
